# Generated by Django 4.0.1 on 2022-03-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=20)),
                ('birthday', models.DateTimeField(verbose_name='birthday is on')),
            ],
        ),
    ]
