# Generated by Django 4.0.1 on 2022-03-11 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthday',
        ),
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 20, 7, 5, 142227, tzinfo=utc)),
        ),
    ]
