# Generated by Django 4.0.3 on 2022-03-14 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_tracker', '0002_remove_person_birthday_person_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateTimeField(default=datetime.datetime(1500, 1, 1, 12, 0)),
        ),
    ]
